### ISSUE TITLE
Login screen before actually starting main application?

### ISSUE THREAD

**Issue by fredrikaverpil** [mherrmann/fbs-tutorial#10]
If the main application requires a login/authorization phase, and I wish to show this before actually showing my main application, what would you advise I do?

Should I call a modal dialog window from my `application_context.py`'s `run` function which would stop and wait for a successful logon before continuing with showing the main application?

**Comment by fredrikaverpil** [comment]
This is what I did and seems to work fine, by the way. I was just interested in hearing if you had any additional thoughts on this "pre-baseapp" phase. I'll close this for now.

**Comment by mherrmann** [comment]
Calling the modal dialog from `AppContext#run(...)` is exactly what I would have done :+1:. (That's how fman does it as well.)

**Comment by fredrikaverpil** [comment]
👌
