### ISSUE TITLE
AppImage Support for Linux

### ISSUE THREAD

**Issue by pintman** [mherrmann/fbs-tutorial#16]
There is no support for Linux when creating an installer. If you have a DMG installer for MacOS it might be easy to create an AppImage for Linux as well.

**Comment by mherrmann** [comment]
You're right. Please see [this thread](https://github.com/mherrmann/fbs/issues/35).

**Comment by pintman** [comment]
Thanks for the hint - didn't recognize that.

**Comment by dridk** [comment]
Is appImage supported ?

**Comment by mherrmann** [comment]
Please see https://github.com/mherrmann/fbs/issues/49.
