### ISSUE TITLE
two minor improvements

### ISSUE THREAD

**Issue by katakombi** [mherrmann/fbs-tutorial#22]
* [x]  would be good to note beforehand you need to install `pip install wheel`.
* [x] same goes for ruby, ruby-gem and npm. I had to install it system-wide - actually would be nice to have this installed locally only!

Thanks, otherwise great tut!

**Comment by mherrmann** [comment]
Hi, I didn't know you had to `pip install wheel`. What happens when you don't?

And I believe the tutorial [says](https://github.com/mherrmann/fbs-tutorial#linux-installer) that you need to install `fpm` (which is what requires ruby etc.):

> On Linux, the installer command requires that you have `fpm`. You can for instance follow [these instructions](https://fpm.readthedocs.io/en/latest/installing.html) to install it.

**Comment by katakombi** [comment]
I got a bunch of errors on `pip install fbs PyQt5==5.9.2 PyInstaller==3.4` which did not say much to me.
After searching I figured wheel was missing, installed it and it worked. Sorry, I don't have the output any more.

Okay, I was being a bit inprecise: You'll get the error *before* you read you'll need to have it installed :) I got the feeling you could possibly add ruby/ruby-gem/npm locally and wouldn't need to point to the external howto which does a system-wide install.

**Comment by mherrmann** [comment]
Good points, and I integrated them. Thanks!
