### ISSUE TITLE
I'm using QtWebEngineWidgets but I can't packing

### ISSUE THREAD

**Issue by like-sinsky** [mherrmann/fbs-tutorial#23]
Please only use this issue tracker for problems with the **tutorial**.
For help with fbs in general, please use:

https://github.com/mherrmann/fbs/issues
I'm using pyside2!
when i run the program them it show this error msg "Could not find QtWebEngineProcess"
How can I add QtWebEngineProcess.app ?

**Comment by mherrmann** [comment]
Okay, so which part of

> Please only use this issue tracker for problems with the tutorial.
> For help with fbs in general, please use:
> https://github.com/mherrmann/fbs/issues

which you quote! Did you not understand?

**Comment by like-sinsky** [comment]
oh sorry..
