### ISSUE TITLE
Uninstaller

### ISSUE THREAD

**Issue by BlitzTechnology** [mherrmann/fbs-tutorial#26]
Please only use this issue tracker for problems with the **tutorial**.
For help with fbs in general, please use:

https://github.com/mherrmann/fbs/issues

I've accidentally install the installer on a wrong dir, and when i uninstall it, it delete all of the file in the dir.
Is it how it should behave?
or i miss something?

**Comment by mherrmann** [comment]
I'm afraid that's a limitation of the current implementation. If you want, you can file it as a bug at https://github.com/mherrmann/fbs/issues.
