### ISSUE TITLE
[help]working with pcraster

### ISSUE THREAD

**Issue by uttu90** [mherrmann/fbs-tutorial#28]
I am developing an application with pcraster (installation [here](http://pcraster.geo.uu.nl/quick-start-guide/)).
python version: 3.6.6
pcraster version: 4.2.1
The problem is I can import and run the application with pcraster but when I freeze the application, it fails because of missing .dll files.
The freeze pcraster folder: 
https://transfer.sh/7rfBT/pcraster%20freeze%202.PNG
https://transfer.sh/S7adP/pcraster%20freeze.PNG

Thanks

**Comment by mherrmann** [comment]
> Please only use this issue tracker for problems with the **tutorial**.

Which part of this was unclear?
