### ISSUE TITLE
failed to execute script fbs_pyinstaller _ hook

### ISSUE THREAD

**Issue by alpha999999999999** [mherrmann/fbs-tutorial#30]
Hello, I have just tried fbs today, then I try to compile .py (pyqt5) to .exe with fbs, when I run command `fbs run` everything work ok but when I clicked to .exe app it throws this error. What happend here ? How I can fix this? 
os: Windows 10
Thank for reading!
![Screenshot from 2019-08-02 07-40-41](https://user-images.githubusercontent.com/40297209/62336087-e2b65500-b4f8-11e9-9114-6606f7273da1.png)
Please only use this issue tracker for problems with the **tutorial**.
For help with fbs in general, please use:

https://github.com/mherrmann/fbs/issues

**Comment by mherrmann** [comment]
Quoting what you yourself wrote:

> Please only use this issue tracker for problems with the tutorial.
> For help with fbs in general, please use:
> https://github.com/mherrmann/fbs/issues
