### ISSUE TITLE
failed to execute script main

### ISSUE THREAD

**Issue by alpha999999999999** [mherrmann/fbs-tutorial#34]
First of all, thank Mr.mherrmann for fbs library 
I  have used fbs to make an installer pyqt5 but file .exe not working (fbs run is worked) 
no import error found when i run fbs clean and fbs freeze --debug, I don't know how to fix this ... 

![Screenshot from 2019-08-17 23-33-28](https://user-images.githubusercontent.com/40297209/63214826-94839180-c147-11e9-8cac-553970b009b9.png)

here is all pakage I used:
* altgraph==0.16.1
* APScheduler==3.6.1
* fbs==0.8.3
* future==0.17.1
* macholib==1.11
* numpy==1.17.0
* pefile==2019.4.18
* PyInstaller==3.4
* PyQt5==5.9.2
* pytz==2019.2
* pywin32==224
* pywin32-ctypes==0.2.0
* sip==4.19.8
* six==1.12.0
* tzlocal==2.0.0
**environment: venv , window10, Pycharm** 
Thank for reading!

Please only use this issue tracker for problems with the **tutorial**.
For help with fbs in general, please use:

https://github.com/mherrmann/fbs/issues

**Comment by mherrmann** [comment]
This is not about the tutorial, is it?

**Comment by alpha999999999999** [comment]
oh my god! I loss again... sorry ... :(
