### ISSUE TITLE
Is there any way to directly produce windows .exe installation files under Ubuntu?

### ISSUE THREAD

**Issue by xdwgood** [mherrmann/fbs-tutorial#35]
Fbs works great under my Ubuntu! It can generate .deb installation files!
But I don't want to install a virtual machine. How can fbs produce .exe installation files under Ubuntu?

Thank you for making us get .deb easy!

**Comment by mherrmann** [comment]
I'm sorry but this is not possible. The only way to get a `.exe` from fbs is to run `fbs freeze` on a Windows machine.

**Comment by xdwgood** [comment]
ok, got it. thanks again
