### ISSUE TITLE
Does any way to keep the NSIS script?

### ISSUE THREAD

**Issue by Truth1987** [mherrmann/fbs-tutorial#36]
So I can add some script I want to, like add icon or adjust compress option.
Then build myself.

**Comment by mherrmann** [comment]
You can copy the [default `Installer.nsi`](https://github.com/mherrmann/fbs/blob/master/fbs/_defaults/src/installer/windows/Installer.nsi) file to `src/installer/windows/Installer.nsi` and then make changes to it.

**Comment by Truth1987** [comment]
Thank you
