### ISSUE TITLE
FileNotFoundError: [Errno 2]  Could not locate resource

### ISSUE THREAD

**Issue by shunmuga-sundaram** [mherrmann/fbs-tutorial#37]
HI I am new to fbs and PyQt
It is very nice tool to generate the executable. I like this very much, Very thankful to your time and effort

I placed the UI file in path "**src/main/icons/resources/test.ui**"

and call UI in code  like
appctxt.get_resource("resources/test.ui")

while I run fbs run, it executes like a charm.
After I create the installer I got the error like
FileNotFoundError: [Errno 2]  Could not locate resource

FileNotFoundError: [Errno 2] Could not locate resource: 'resources/test.ui'
[26071] Failed to execute script main

The installer does not consider those files while generating the execution. is i need to mention those files? please guide me

**Comment by mherrmann** [comment]
Hi, place it in `src/main/resources/base/test.ui` and call `appctxt.get_resource('test.ui')`.

**Comment by shunmuga-sundaram** [comment]
Thank you mherrmann, for your reply
After I changed the folder path src/main/resources/base/test.ui

now I am not able to run the project using **fbs run**
**FileNotFoundError: [Errno 2] Could not locate resource: 'test.ui'**

while i execute
print(appctxt.get_resource(''))
it shows
**/home/sundar/Pictures/pyqtlearn/src/main/icons**

is I miss any config statement?

Thanks in advance.

**Comment by mherrmann** [comment]
Please ask on StackOverflow. I'm too busy with my own projects and don't have time to help. Sorry.

**Comment by shunmuga-sundaram** [comment]
After placed **src/main/resources/base/test.ui** it is working fine. I have placed a spelling mistake that is the error. Thank you mherrmann for your help :)
