### ISSUE TITLE
Your App's Bundle ID is Empty

### ISSUE THREAD

**Issue by ScarlettCharlie** [mherrmann/fbs-tutorial#45]
System: MacOS 0.15.5

Everything was okay but...oops

I followed every step according to the Apple Developer's website
Created an App ID, installed certificates and everything
But When I used Transporter to upload the .apk file it shows this:

Your App's Bundle ID is Empty

If I use Application Loader instead, the error is:

You must supply a CFBundleIdentifier for this request.

I googled it and checked the info.plist.
Bundle OS Type code's key and value are both alright...
Strange thing is, even the .spec file has made everything correct about bundle id.

Hmm could you tell what is going on?
Do I have to re-install or recreate an App ID or re-project it?

@mherrmann One more step and I can upload my app! THANK YOU!!!!!!!!!!

**Comment by ScarlettCharlie** [comment]
@mherrmann Do not ignore this issue, please. Giving no response may be understood as a sign of disrespect. Not to mention how much time of a developer your ignorance can cause.

This is definitely not my fault because I followed each step of your doc.
Fbs asked me to provide app's name, app id and etc. and I did them all correctly.

Obviously there is something wrong with fbs. It didn't include any of my certificates or identifiers provided by Apple Developer Center.

This is not complaining. This is about telling you something that neither you and I have expected and YOU are the one to solve it by far.

Don't make my issue(s) the only type without response. This is disrespectful.

**Comment by mherrmann** [comment]
A sign of disrespect? You are using something which I made available, in my spare time, for free. And you also want me to spend time helping you - for free? And if I don't, you say I'm disrespectful?

i didn't even read the rest of your message. Closing this issue. I never want to see you here again.

**Comment by ScarlettCharlie** [comment]
Oh really?! SO THIS IS A BUG ABOUT PAYING? THEN TELL EVERYONE TO PAY BEFORE USE!
You think I want to see you here? 
You think I don't want to buy you app?
I am trying to verify that this app can make my. pkg deliverable first then buy it.

You closed this issue meaning that the notification can be seen, right? 
Other issues are made by paid users? Is that the case?
It's not about you wish to see me here or not. It's about you being responsible for this.

Your App Didn't Packed My .pkg file successfully, this is not about payment.

BEING THE ONLY ONE WHOSE ISSUE HAS NEVER BEEN REPLIED, I AM ASTONISHED THAT YOU EVEN DARED TO TALK TO ME LIKE THIS.

**Comment by mherrmann** [comment]
> It's about you being responsible for this.

I'm really surprised where this expectation comes from. I have absolutely 0 obligation to you. Just because I make something open source does not mean I need to reply to issues, help people with their scripts, provide maintenance or any of those things. If you do not understand this, then we don't have any basis for discussion. I'm too busy to fight with you, and like I said no obligation to even get back to you. So I'll stop doing that now.

**Comment by ScarlettCharlie** [comment]
I never intended to fight with you, either. Since you don't think you have this obligation, I will open an issue and I WILL NOT EXPECT YOU TO ANSWER IT, JUST TO LET KNOW THAT THIS ISN'T A PAYMENT BUG. And please realize that I have 0 bad intensions and I didn't even wish to ask any questions if I had solutions. I didn't develop this, so obviously I do not have this obligation, either. Yes you are all correct and I didn't do packaging wrong, and I will pay if I use. But this bug is not about payment, and I just wish others might see. I am busy too so I have to upload my app soon. I am a desperate developer looking for help, not a trouble maker ciber-bullying you.

**Comment by ScarlettCharlie** [comment]
> > It's about you being responsible for this.
> 
> I'm really surprised where this expectation comes from. I have absolutely 0 obligation to you. Just because I make something open source does not mean I need to reply to issues, help people with their scripts, provide maintenance or any of those things. If you do not understand this, then we don't have any basis for discussion. I'm too busy to fight with you, and like I said no obligation to even get back to you. So I'll stop doing that now.

I never intended to fight with you, either. Since you don't think you have this obligation, I will open an issue and I WILL NOT EXPECT YOU TO ANSWER IT, JUST TO LET KNOW THAT THIS ISN'T A PAYMENT BUG. And please realize that I have 0 bad intensions and I didn't even wish to ask any questions if I had solutions. I didn't develop this, so obviously I do not have this obligation, either. Yes you are all correct and I didn't do packaging wrong, and I will pay if I use. But this bug is not about payment, and I just wish others might see. I am busy too so I have to upload my app soon. I am a desperate developer looking for help, not a trouble maker ciber-bullying you.
