### ISSUE TITLE
readme.md // download link outdated

### ISSUE THREAD

**Issue by ChrisOKay** [mherrmann/fbs-tutorial#49]
The [download link](https://github.com/mherrmann/fbs-tutorial/archive/master.zip) in the [readme.md](https://github.com/mherrmann/fbs-tutorial/blob/705f7d7db8df2b5885125632b2035882bde1aaaa/README.md) seems to be incorrect/outdated. In this zip, there is no requirements.txt, no src folder, just a plain main.py. I guess this is not intended and should rather point to the current version of the tutorial? I don't know how to link to the latest version without [releases](https://docs.github.com/en/github/administering-a-repository/linking-to-releases), elsewise I would change it directly.

...
on second thought, the whole tutorial seems to be outdated and non-functional? requirements.txt requires fbs==0.1.0 instead of 0.9.0? main.py inside main/python/tutorial imports tutorial.application_context, so it should rather be in main/python...? I am confused.

**Comment by mherrmann** [comment]
The version of README.md you are referring to is old and indeed broken. Please refer to the latest one, which you can find displayed at https://github.com/mherrmann/fbs-tutorial.
