### ISSUE TITLE
How to modify NSIS settings?

### ISSUE THREAD

**Issue by fredrikaverpil** [mherrmann/fbs-tutorial#5]
Where should I modify the NSIS settings used when performing a `python -m fbs installer`?

For example, I'd like to change the default install path from `C:\Program Files (x86)\Tutorial` to `C:\Program Files\Tutorial`, since my Python app is 64-bit.

**Comment by mherrmann** [comment]
Hi Fredrik, good question. Right now, the necessary file `Setup.nsi` is contained in `fbs` and so "can't" be modified. My gut feeling would be to move it out of `fbs` and into `fbs-tutorial`, say at `src/main/Installer.nsi`. What do you think?

**Comment by fredrikaverpil** [comment]
Sure. I don't have a preference of exact location (other than easily being able to modify it) so I think that sounds good.

**Comment by mherrmann** [comment]
Okay. I updated the tutorial and fbs now. You can customize the default install location by changing `$PROGRAMFILES` to `$PROGRAMFILES64` in [Installer.nsi](https://github.com/mherrmann/fbs-tutorial/blob/705f7d7db8df2b5885125632b2035882bde1aaaa/src/main/Installer.nsi#L19).

**Comment by fredrikaverpil** [comment]
Very nice, thank you! :)

**Comment by mherrmann** [comment]
My pleasure!

**Comment by ChrisOKay** [comment]
So, I tried to implement that technique, but a custom installer.nsi placed in src/main was ignored by fbs installer and the default one was generated. I then tried to follow the tutorial, I accidentally followed the blob link here and then reached the outdated readme.md, which lead to issue #49 .
The latest tutorial does not seem to cover any custom nsi files anymore.
Long story short: Is it still possible to implement a custom installer.nsi (if so, how?), or is that a thing of the past?

**Comment by mherrmann** [comment]
I think you need to place it in `src/installer/windows/Installer.nsi`. See the built-in one in fbs's source directory in fbs/_defaults.

**Comment by ChrisOKay** [comment]
You thought correctly! Thanks for the additional hint on the _defaults folder to look up the structure, I did not know about that one yet.

**Comment by abood91** [comment]
Hi @mherrmann  Is it possible to provide example on how can use the `src/installer/windows/Installer.nsi` and provide AceesControl  modification ?, I am after changing file permissions in resource directory, as my app can read but not write to that file

**Comment by mherrmann** [comment]
@abood91 sorry this is beyond the scope of my support. It's an NSIS question. I'd recommend you ask on StackOverflow.

**Comment by abood91** [comment]
@mherrmann Is there a possibility to sign the uninstaller as well ?  I think this should be part of the implementation of the sign_installer function ?

**Comment by mherrmann** [comment]
@abood91 You're right. The uninstaller probably should be signed by sign_installer.
