### ISSUE TITLE
PyQt 5.9.2 appears broken

### ISSUE THREAD

**Issue by bicarlsen** [mherrmann/fbs-tutorial#53]
When running `pip install PyQt5==5.9.2` I receive the error
> ERROR: Could not find a version that satisfies the requirement sip<4.20,>=4.19.4 (from PyQt5==5.9.2) (from versions: 5.0.0, 5.0.1, 5.1.0, 5.1.1, 5.1.2, 5.2.0, 5.3.0, 5.4.0, 5.5.0)
ERROR: No matching distribution found for sip<4.20,>=4.19.4 (from PyQt5==5.9.2)

**Comment by bicarlsen** [comment]
This appears to only be an issue for Python version above 3.6, I haven't tested the exact version at which it breaks. However, because this is a tutorial, and it appears one of the most common errors is to use an incompatible Python version, it may be worth mentioning somewhere in the tutorial the required Python versions.

**Comment by mherrmann** [comment]
I'll try to make the following from the README even clearer:

> The only prerequisite is Python 3.5 or 3.6. Python 3.7 is not yet officially supported. It may or may not work.

**Comment by bicarlsen** [comment]
I think it may be helpful to state it a bit more forcefully too. Something like
> **Only Python versions 3.5 and 3.6 are supported. Other versions will likely give errors.**

on it's own line.
