### ISSUE TITLE
fpm Insall Link Broken

### ISSUE THREAD

**Issue by bicarlsen** [mherrmann/fbs-tutorial#58]
In the [`Creating an installer > Linux installer`](https://github.com/mherrmann/fbs-tutorial#linux-installer) section there is a link to the fpm install instructions which currently points to https://fpm.readthedocs.io/en/latest/installing.html which is a broken link.

I believe the correct link is now at https://fpm.readthedocs.io/en/latest/installation.html

**Comment by mherrmann** [comment]
Thanks! I fixed it.
