### ISSUE TITLE
Structuring main app as submodule

### ISSUE THREAD

**Issue by fredrikaverpil** [mherrmann/fbs-tutorial#6]
Hello!

The fbs-tutorial is a nice way to explain how fbs works. I'm now thinking about how I can structure my app(s) around fbs-tutorial.

Say I want to develop my app using git. How would I reap the benefits of future fbs-tutorial updates?
Let's say, for example, that I develop my own app as a git submodule of fbs-tutorial (or the other way around; having fbs-tutorial as a submodule of my app).

Today, it feels quite fine to manually track updates to fbs-tutorial, like the recent change where the [NSIS settings were moved](https://github.com/mherrmann/fbs-tutorial/commit/705f7d7db8df2b5885125632b2035882bde1aaaa#diff-dc06f12fe6d19dd8f74a0003d93331cd). But down the line, changes may get harder to track.

Before I propose any suggestions on app layout, @mherrmann what would you recommend?

**Comment by mherrmann** [comment]
Hi Fredrik!

Imho, the best approach is to copy the source code of fbs-tutorial and adjust it to your needs; Treat it as if it were code you wrote yourself. If a new version of fbs-tutorial comes out, I would then just manually copy over the changes. It shouldn't be too much, in particular the structure should remain mostly the same, and by updating the `fbs` dependency to higher versions you get the body of the new functionality. In my experience, git submodules are a bit tedious to work with, so I would avoid them.

**Comment by fredrikaverpil** [comment]
Ok - I might just do this for now then.

> In my experience, git submodules are a bit tedious to work with, so I would avoid them.

Yes, I concur with this statement.
