### ISSUE TITLE
Using Qt.py instead of PyQt5 import

### ISSUE THREAD

**Issue by fredrikaverpil** [mherrmann/fbs-tutorial#7]
Hi again!

When I freeze my fbs-tutorial, it works great -- even when I use PySide2. 😄 

However, I would like to actually use [Qt.py](https://github.com/mottosso/Qt.py) in my source code, and then let Qt.py decide whether to pick up PySide2, PyQt5 or any other binding available. I realize this doesn't make sense in most use cases when producing a standalone app, but in my case, I wish some of my code base to be shared among different applications (including the case where the code is being executed in a PySide(1) environment).

When I use `from Qt import QtWidgets` in `application_context.py`, I can successfully `python -m fbs run` and `python -m fbs freeze`, but when I try to run my standalone app, it b0rks with the following and exits:

![image](https://user-images.githubusercontent.com/994357/36966850-61c70744-205e-11e8-8cf2-157199bf4f7c.png)

I am aware of that the issue is most likely on the Qt.py end (and/or possibly with PyInstaller) and perhaps not so much with fbs, but I'm trying to figure out what I could possibly do to fix this -- and so I'm posting this issue to just see if you have any ideas on where I should start looking for clues...

I've switched the fbs freeze/PyInstaller log level to `INFO` but the logs are identical when I freeze with PySide2 and with Qt.py. I've then moved on to check the `target/PyInstaller/Tutorial/warnTutorial.txt` but it doesn't say anything useful in terms of being unable to pick something specific up which seems related to my issue.

When I watch the target/Tutorial folder being built, I can see that the PyQt5 DLLs are being put there successfully, just like when using PyQt5 (and not Qt.py).

**Comment by mherrmann** [comment]
> When I freeze my fbs-tutorial, it works great -- even when I use PySide2. :smile:

:+1: that's awesome! Long-term, it would be amazing if fbs could simply use PySide2 instead of PyQt.

To debug this, I would remove the `--windowed` flag from `fbs/freeze/windows.py`. Then, run the .exe from a command prompt. You should get debug output this way that should hopefully give more insights than "Failed to execute script main".

Hope this helps. If not, let me know.

Cheers,
M

**Comment by fredrikaverpil** [comment]
> To debug this, I would remove the --windowed flag from fbs/freeze/windows.py

Thanks, this helped. I was using an older version of Qt.py (v1.0.0b3) and when updating to the very latest (v1.1.0), the problem went away) and I can now skip defining the binding explicitly, and use Qt.py instead! 👍 

I'm somewhat aware of what caused the issue. There was a change in Qt.py, where the whole .ui file loading behavior was overhauled in Qt.py (v1.0.0b5 I believe). This overhaul work fixed the issues I was now hitting.
