### ISSUE TITLE
Question: support multiple applications out of the box?

### ISSUE THREAD

**Issue by fredrikaverpil** [mherrmann/fbs-tutorial#9]
I'm sometimes a little confused on whether to set up an issue in fbs or here, in fbs-tutorial... :wink: but here goes...

So I'm [dabbling](https://github.com/fredrikaverpil/fbs-tutorial/tree/multibundle) with setting up "secondary" applications such as a `cmdline.exe` next to my main `Tutorial.exe`. Right now, I need to use a custom `build.py` script to have this secondary application become frozen.
-- By the way; Perhaps it's unwise to refer to such applications as "secondary", as their functionality may be essential to the primary application.

@mherrmann do you think it would be worthwile to support multiple applications out of the box?
I'm thinking being able to specify which one to run on `python -m fbs run`, freeze all of them on `python -m fbs freeze` and so on.

I love the simplicity and straight-forwardness of fbs-tutorial. This type of change would imply you need to put apps inside of a folder for the macOS installer and some other changes... which may (or may not) make the whole approach of fbs slightly more complex (and hopefully not unreliable). I totally respect and understand if you feel that catering to use cases like this would make the code (or reliability) unnecessarily complex, even if I personally believe that being able to bundle more than one application isn't really such an edge case.

It's just a thought, would be interested to hear what you think about it. 😄

**Comment by mherrmann** [comment]
Hey Fredrik,

let's have such discussions in [fbs](https://github.com/mherrmann/fbs) please :-) I commented on another issue you opened there.

M

**Comment by fredrikaverpil** [comment]
Ok, I see this question is kind of brought up in https://github.com/mherrmann/fbs/issues/14 so let's move the discussion there!
